import { BsFiletypeCss, BsFiletypeScss } from "react-icons/bs";
import {
  FaNodeJs,
  FaReact,
  FaLaravel,
  FaVuejs,
  FaHtml5,
  FaSass,
  FaAws,
  FaLinux,
  FaDocker,
  FaNpm,
  FaAngular,
  FaJava,
  FaJenkins,
  FaGitlab,
  FaLess,
  FaFigma,
} from "react-icons/fa";
import { IoIosLink, IoIosStarOutline, IoLogoJavascript } from "react-icons/io";
import { IoColorPaletteOutline, IoLogoFirebase } from "react-icons/io5";
import { LiaMoneyCheckSolid } from "react-icons/lia";
import {
  SiTypescript,
  SiNextdotjs,
  SiTailwindcss,
  SiWebpack,
  SiDotnet,
  SiCsharp,
  SiTestinglibrary,
  SiRedux,
  SiKubernetes,
  SiEslint,
  SiSvelte,
  SiTrpc,
  SiPrisma,
  SiRuby,
  SiReactquery,
  SiJest,
  SiNestjs,
  SiGradle,
  SiMocha,
  SiStyledcomponents,
  SiVercel,
  SiApachekafka,
  SiMongodb,
} from "react-icons/si";
import { TbApi, TbBrandCypress, TbBrandVite, TbSql } from "react-icons/tb";
import {
  Phone,
  Website,
  Linkedin,
  Github,
  Twitter,
  Vk,
  X,
  Glassdoor,
  Gmail,
  LinkedinColor,
  Diamond,
  Bird,
  Email,
  Location,
} from "~/components/icons";
import { VscJson } from "react-icons/vsc";
import { DiJqueryLogo, DiMysql } from "react-icons/di";
import { DiPostgresql } from "react-icons/di";
import { DiScrum } from "react-icons/di";
import { GrGraphQl } from "react-icons/gr";
import { DiRedis } from "react-icons/di";

// Exact means "==="
// Partial means "includes"
// dotnet is unique enough to be exact
// .net is not unique enough to be exact (`kek.net` would then be matched)

export const iconsMap = [
  { partial: ["email"], icon: Email },
  { partial: ["phone"], icon: Phone },
  { partial: ["address", "location"], icon: Location },
  { exact: ["website"], icon: Website },
  { partial: ["linkedin"], icon: Linkedin },
  { partial: ["github"], exact: ["git"], icon: Github },
  { partial: ["gitlab"], icon: FaGitlab },
  { exact: ["twitter"], icon: Twitter },
  { exact: ["vk"], icon: Vk },
  { exact: ["x"], icon: X },
  { exact: ["glassdoor"], icon: Glassdoor },
  { exact: ["gmail"], icon: Gmail },
  { exact: ["linkedinColor"], icon: LinkedinColor },
  { exact: ["diamond"], icon: Diamond },
  { exact: ["bird"], icon: Bird },
  { exact: ["check"], icon: LiaMoneyCheckSolid },
  { exact: ["star"], icon: IoIosStarOutline },
  { partial: ["jquery"], icon: DiJqueryLogo },
  { exact: ["kafka"], icon: SiApachekafka },
  {
    partial: ["javascript", "ecmascript", "es6", "es5"],
    exact: ["js"],
    icon: IoLogoJavascript,
  },
  { partial: ["typescript"], exact: ["ts"], icon: SiTypescript },
  { partial: ["firebase"], icon: IoLogoFirebase },
  { partial: ["mongo", "mongoose"], icon: SiMongodb },
  {
    partial: ["nodejs", "node.js"],
    icon: FaNodeJs,
  },
  {
    exact: ["react"],
    partial: ["reactjs", "react.js", "react native"],
    icon: FaReact,
  },
  { exact: ["laravel"], icon: FaLaravel },
  { partial: ["nextjs", "next.js"], icon: SiNextdotjs },
  { partial: ["tailwind", "tailwindcss", "tailwind css"], icon: SiTailwindcss },
  { partial: ["vue.js", "vue", "vuejs"], icon: FaVuejs },
  { partial: ["html5", "html"], icon: FaHtml5 },
  { exact: ["css3", "css"], icon: BsFiletypeCss },
  { partial: ["scss"], icon: BsFiletypeScss },
  { partial: ["RESTful APIs", "REST API"], icon: TbApi },
  { exact: ["json"], icon: VscJson },
  { partial: ["webpack"], icon: SiWebpack },
  { exact: ["design"], icon: IoColorPaletteOutline },
  { partial: ["mysql"], icon: DiMysql },
  { partial: ["postgres"], icon: DiPostgresql },
  { partial: ["sass"], icon: FaSass },
  {
    exact: [".net", "dotnet"],
    partial: ["dotnet", ".net core"],
    icon: SiDotnet,
  },
  { partial: ["c#"], icon: SiCsharp },
  { exact: ["cypress"], icon: TbBrandCypress },
  { partial: ["react testing library"], icon: SiTestinglibrary },
  { partial: ["redux", "redux toolkit"], icon: SiRedux },
  { partial: ["scrum"], icon: DiScrum },
  { partial: ["kubernetes"], icon: SiKubernetes },
  { partial: ["eslint"], icon: SiEslint },
  { partial: ["aws"], icon: FaAws },
  { partial: ["graphql"], icon: GrGraphQl },
  { partial: ["svelte"], icon: SiSvelte },
  { partial: ["trpc"], icon: SiTrpc },
  { partial: ["linux"], icon: FaLinux },
  { partial: ["docker"], icon: FaDocker },
  { exact: ["prisma", "prisma orm"], icon: SiPrisma },
  { exact: ["redis"], icon: DiRedis },
  { exact: ["npm"], icon: FaNpm },
  { exact: ["vite"], icon: TbBrandVite },
  { partial: ["ruby on rails"], icon: SiRuby },
  { partial: ["react query", "reactquery", "tanstack"], icon: SiReactquery },
  { partial: ["jest"], icon: SiJest },
  { exact: ["angular", "angular.js"], icon: FaAngular },
  { exact: ["nestjs", "nest.js"], icon: SiNestjs },
  { exact: ["sql"], icon: TbSql },
  { exact: ["java"], icon: FaJava },
  { exact: ["gradle"], icon: SiGradle },
  { partial: ["jenkins"], icon: FaJenkins },
  { partial: ["mocha"], icon: SiMocha },
  { partial: ["styled-components"], icon: SiStyledcomponents },
  { partial: ["vercel"], icon: SiVercel },
  { exact: ["less"], icon: FaLess },
  { partial: ["figma"], icon: FaFigma },
  { exact: ["link"], icon: IoIosLink },
];
