export const IT_COMPANY_NAMES = [
  "Microsoft",
  "Apple",
  "Google",
  "Amazon Web Services",
  "Oracle",
  "IBM",
  "Facebook",
  "Adobe Systems",
  "Salesforce",
  "SAP",
  "Cisco Systems",
  "Intel",
  "NVIDIA",
  "AMD",
  "Qualcomm",
  "VMware",
  "Red Hat",
  "Symantec",
  "Dell Technologies",
  "Hewlett Packard Enterprise",
  "Lenovo",
  "Accenture",
  "Infosys",
  "Wipro",
  "TCS",
  "Cognizant",
  "Capgemini",
  "Atlassian",
  "Slack Technologies",
  "Dropbox",
  "Zoom Video Communications",
  "Twilio",
  "Palantir Technologies",
  "ServiceNow",
  "Nutanix",
  "Splunk",
  "Zoho",
  "Rackspace",
  "GoDaddy",
  "Akamai Technologies",
  "Cloudflare",
  "GitLab",
  "GitHub",
  "Docker",
  "JetBrains",
  "UiPath",
  "Snowflake",
  "Elastic",
  "MongoDB",
  "Tableau Software",
  "Teradata",
  "SAS Institute",
  "Epic Systems",
  "Cerner",
  "Intuit",
  "Square",
  "Stripe",
  "Shopify",
  "McAfee",
  "Trend Micro",
  "Kaspersky Lab",
  "Avast",
  "AVG Technologies",
  "Fortinet",
  "Palo Alto Networks",
  "Check Point Software Technologies",
  "F5 Networks",
  "Citrix Systems",
  "LogMeIn",
  "TeamViewer",
  "Trello",
  "Asana",
  "Basecamp",
  "Evernote",
  "Autodesk",
  "Unity Technologies",
  "Electronic Arts",
  "Activision Blizzard",
  "Ubisoft",
  "NetApp",
  "Pure Storage",
  "Micron Technology",
  "Kingston Technology",
  "Western Digital",
  "Seagate Technology",
  "Broadcom",
  "ARM Holdings",
  "Ericsson",
  "Amdocs",
  "NTT Data",
  "HCL Technologies",
  "Tech Mahindra",
  "CDW",
  "DXC Technology",
  "Pegasystems",
  "Mulesoft",
  "HubSpot",
  "Mailchimp",
  "Zendesk",
  "Freshworks",
  "LINE Corporation",
  "Naver Corporation",
  "Baidu",
  "Tencent",
  "Alibaba Cloud",
  "ByteDance",
  "Rakuten",
  "SoftBank",
  "Grab",
  "Gojek",
  "Tokopedia",
  "Traveloka",
  "Ola Cabs",
  "Paytm",
  "Zomato",
  "Swiggy",
  "Didi Chuxing",
  "JD.com",
  "Xiaomi",
  "Huawei",
  "ZTE",
  "OPPO",
  "Vivo",
  "Meituan-Dianping",
  "Coupang",
  "NAVER",
  "Kakao",
  "Yandex",
  "Mail.Ru Group",
  "OLX Group",
  "Delivery Hero",
  "Just Eat Takeaway",
  "Zalando",
  "Wix.com",
  "JFrog",
  "SolarWinds",
  "Dynatrace",
  "CrowdStrike",
  "Fastly",
  "Datadog",
  "Okta",
  "RingCentral",
];
