import type { ContactEntry, LanguageEntry, SkillEntry } from "@prisma/client";
import type { PartialVacancy } from "../types";

type Uuidv4 = string;

export type BulletPoint = {
  id: Uuidv4;
  value: string;
};

export type CvExperienceEntry = {
  id: Uuidv4;
  place: string;
  title: string;
  period: string;
  bullets: BulletPoint[];
  image: string;
  skills?: CvSkill[];
};

export type CvEducationEntry = {
  id: Uuidv4;
  place: string;
  title: string;
  period: string;
  description: string;
  image: string;
};

export type CvSkill = Pick<SkillEntry, "id" | "name">;
export type CvLanguage = Pick<LanguageEntry, "id" | "name" | "value">;
export type CvContact = Pick<ContactEntry, "id" | "name" | "value">;

export type Cv = {
  id: Uuidv4;
  vacancyId: Uuidv4;
  userName: string;
  jobTitle: string;
  summary: string;
  experience: CvExperienceEntry[];
  education: CvEducationEntry[];
  skills: CvSkill[];
  languages: CvLanguage[];
  contact: CvContact[];
  fileName: string;

  coverLetter?: string;
};

/**
 * Generated by AI. Naming could be better. 😅
 */
export type Gen = {
  vacancy: PartialVacancy;
  vacancyResponsibilities: string[];
  vacancySkills: string[];
  salary: string;
  location: string;
  requiredRemote: string;
  requiredSeniority: string;
  employmentType: string;

  /**
   * Generated to be used in cv.
   */
  professionalSummary: string;
  experience: CvExperienceEntry[];
  skills: CvSkill[];
};
